name: CI

# trigger this workflow every push action
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: mvn clean
      run: |
        mvn clean

    - name: mvn install
      run: |
        mvn install
    - name: mvn test
      run: |
        mvn test
      env:
        CI: true

    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Deploy to Heroku
      run: |
        git push heroku main